"""report.md: what the papers ask, topic weightage, coverage gaps and anything unverified (BRIEF section 2)."""
from __future__ import annotations

from ..course import CourseConfig
from .models import PapersFile, TopicsFile

TYPE_WORD = {"long-explain": "explain", "code-write": "write code", "code-trace": "trace code", "code-fix": "fix code"}


def pct(x: float) -> str:
    return f"{x * 100:.0f}%" if x >= 0.095 or x == 0 else f"{x * 100:.1f}%"


def num(x: float) -> str:
    return f"{x:.1f}".rstrip("0").rstrip(".")


class Labels:
    def __init__(self, papers: PapersFile | None, topics: TopicsFile):
        self.p = {p.id: p for p in papers.papers} if papers else {}
        self.q = {q.id: q for q in papers.questions} if papers else {}
        self.t = {t.id: t for t in topics.topics}

    def paper(self, pid: str) -> str:
        p = self.p[pid]
        if p.kind == "sample":
            return "sample questions" if p.year is None else f"{p.year} sample questions"
        return f"{p.year} {p.exam}" if p.year else p.id

    def q_short(self, qid: str) -> str:
        q = self.q[qid]
        return f"{self.paper(q.paper)} Q{q.number}" + (f" [{num(q.marks)}]" if q.marks is not None else "")

    def topic(self, tid: str) -> str:
        return self.t[tid].name if tid in self.t else tid


def render(cfg: CourseConfig, w: dict, topics: TopicsFile, papers: PapersFile | None, index: dict) -> str:
    L = Labels(papers, topics)
    title = " ".join(x for x in (cfg.code, cfg.name) if x) or "Course"
    out = [f"# {title}: exam report", "",
           "> Generated by `studymap report` from `analysis/topics.json` and `analysis/papers.json`. "
           "Edit those files, not this one; every number below is recomputed from them.", ""]
    exams = w["exams"]
    has_papers = papers is not None and any(p.kind == "exam" for p in papers.papers)

    # ------------------------------------------------------------------ at a glance
    out += ["## At a glance", ""]
    if not has_papers:
        out += ["**No past papers yet.** Topic weights below come from slide emphasis alone (how many slides "
                "each topic gets); treat them as a rough guide. Add papers to `papers/` and re-run to sharpen them.", ""]
    for e in exams:
        head = f"**{e['name']}**" + (f" ({num(e['weight'])}% of the grade)" if e["weight"] is not None else "")
        out.append(f"- {head}" + (f" — {e['format']}" if e["format"] else ""))
        basis = {"papers+slides": f"{len(e['papers'])} past paper{'s' if len(e['papers']) != 1 else ''} blended with slide emphasis "
                                  f"(slides count {pct(e['slide_prior'])})",
                 "papers": f"{len(e['papers'])} past papers", "slides": "slide emphasis only (no papers for this exam yet)",
                 "none": "nothing to go on yet"}[e["basis"]]
        out.append(f"  - Weights from {basis}.")
        top = [t for t in e["topics"] if t["share"] > 0][:5]
        if top:
            rt = e["reference_total"]
            out.append("  - Top topics: " + "; ".join(
                f"{L.topic(t['id'])} {pct(t['share'])}" + (f" (≈{num(t['share'] * rt)}/{num(rt)} marks)" if rt else "")
                for t in top) + ".")
        if e["modes"]:
            out.append("  - By marks: " + " · ".join(f"{m['mode']} {pct(m['share'])}" for m in e["modes"]) + ".")
    out.append("")
    if papers and papers.notes:
        out += ["**Read this first:**", ""] + [f"- {n}" for n in papers.notes] + [""]

    # ------------------------------------------------------------------ patterns
    if papers and papers.patterns:
        out += ["## Recurring patterns", ""]
        for pat in papers.patterns:
            out.append(f"- {pat.text}  ")
            out.append("  *" + "; ".join(L.q_short(q) for q in pat.questions) + "*")
        out.append("")

    # ------------------------------------------------------------------ weightage
    out += ["## Topic weightage", ""]
    for e in exams:
        pids = [p["id"] for p in e["papers"]]
        rt = e["reference_total"]
        out.append(f"### {e['name']}" + (f" ({num(e['weight'])}% of the grade)" if e["weight"] is not None else ""))
        out.append("")
        if e["basis"] == "slides":
            out += ["No papers for this exam yet: shares are slide emphasis only.", ""]
        head = ["#", "Topic", "Share"] + ([f"≈ marks /{num(rt)}"] if rt else []) + [L.paper(p) for p in pids] + \
               (["Samples"] if e["samples"] else []) + ["Slides"]
        out += ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
        emph = {t["id"]: t["emphasis"] for t in w["topics"]}
        for i, t in enumerate(e["topics"], 1):
            if t["share"] == 0 and not t["sample_questions"]:
                continue
            row = [str(i), L.topic(t["id"]), pct(t["share"])] + ([num(t["share"] * rt)] if rt else [])
            row += [num(t["marks"][p]) if p in t["marks"] else "·" for p in pids]
            row += [str(len(t["sample_questions"])) if t["sample_questions"] else "·"] if e["samples"] else []
            row += [str(emph[t["id"]]) if emph[t["id"]] else "·"]
            out.append("| " + " | ".join(row) + " |")
        zero = [L.topic(t["id"]) for t in e["topics"] if t["share"] == 0 and not t["sample_questions"]]
        if zero:
            out += ["", f"Not weighted for this exam: {', '.join(zero)}."]
        out.append("")
        if e["types"]:
            out += [f"Question types in the {e['name']} papers, by share of marks: " + " · ".join(
                f"{TYPE_WORD.get(x['type'], x['type'])} {pct(x['share'])} ({x['count']} q)" for x in e["types"]) + ".", ""]

    # ------------------------------------------------------------------ study order
    out += ["## Suggested study order", "",
            "Whole course, by expected share of the grade" + ("" if w["weighted"] else " (exam weights missing from course.yaml: exams count equally)")
            + ". Mode is how the papers ask it: **apply** = practise problems, **understand** = be able to explain, "
            "**recall** = memorise.", ""]
    out += ["| # | Topic | Weight | Mode | Asked | Points |", "|---|---|---|---|---|---|"]
    for i, t in enumerate(w["topics"], 1):
        out.append(f"| {i} | {t['name']} | {t['weight']} | {t['mode'] or '·'} | {len(t['questions']) or '·'} | {t['points']:.2f} |")
    out.append("")

    # ------------------------------------------------------------------ repeats
    if w["repeats"]:
        out += ["## Asked again across papers", ""]
        for g in w["repeats"]:
            out.append("- " + " ↔ ".join(L.q_short(q) for q in g))
        out.append("")

    # ------------------------------------------------------------------ papers
    if papers:
        out += ["## Papers analysed", ""]
        for p in papers.papers:
            qs = [q for q in papers.questions if q.paper == p.id]
            meta = [f"{len(qs)} questions"]
            if p.total_marks is not None:
                meta.append(f"{num(p.total_marks)} marks")
            if p.duration_min:
                meta.append(f"{p.duration_min} min")
            if p.keys:
                meta.append("key: " + ", ".join(f"{k.path} ({k.status})" for k in p.keys))
            else:
                meta.append("no key")
            if p.transcribed_from_image:
                meta.append("transcribed from scans")
            if p.relevance < 1:
                meta.append(f"counted at {pct(p.relevance)} weight")
            out += [f"### {L.paper(p.id)} — `{p.path}`", "", " · ".join(meta) + ".", ""]
            if p.relevance < 1:
                out += [f"Why reduced weight: {p.relevance_reason}", ""]
            if p.notes:
                out += [p.notes, ""]
            out += ["| Q | Marks | Type | Mode | Difficulty | Topics | Answer |", "|---|---|---|---|---|---|---|"]
            for q in qs:
                ans = "·" if not q.answer else ("key" + (" ⚠" if q.answer.caveat else ""))
                topics_s = ", ".join(L.topic(t) for t in q.topics) or f"*unmapped: {q.unmapped_reason}*"
                out.append(f"| {q.number} | {num(q.marks) if q.marks is not None else '·'} | {q.type} | {q.mode} | "
                           f"{q.difficulty} | {topics_s} | {ans} |")
            out.append("")

    # ------------------------------------------------------------------ coverage
    cov = w["coverage"]
    out += ["## Coverage", ""]
    out.append(f"- **Unmapped questions: {len(cov['unmapped'])}.**" + ("" if not cov["unmapped"] else " " + "; ".join(
        f"{L.q_short(u['id'])}: {u['reason']}" for u in cov["unmapped"])))
    if cov["not_in_slides"]:
        out.append("- **Asked in papers but not in your slides:** " + "; ".join(
            f"{t['name']} ({', '.join(L.q_short(q) for q in t['questions'])})" for t in cov["not_in_slides"]) + ".")
    out.append(f"- **Slides covered by a topic:** {cov['slides_covered']} of {cov['slides_total']} "
               f"(near-duplicates counted once; {cov['deliberately_uncovered']} left out on purpose, e.g. title and admin slides).")
    if cov["uncovered_slides"]:
        out.append("- **Slides no topic covers yet:**")
        for g in cov["uncovered_slides"]:
            out.append(f"  - `{g['path']}` {g['pages']}" + (f": {'; '.join(g['titles'])}" if g["titles"] else ""))
    if cov["unanalysed_papers"]:
        out.append("- **Papers not analysed yet:** " + ", ".join(f"`{p}`" for p in cov["unanalysed_papers"]))
    out.append("")

    # ------------------------------------------------------------------ unverified
    un = w["unverified"]
    out += ["## Unverified", ""]
    if not any(un.values()):
        out += ["Nothing.", ""]
    else:
        if un["transcribed"]:
            out.append(f"- **Transcribed from scans ({len(un['transcribed'])}):** check the wording against the page images "
                       "if an answer depends on a detail.")
        if un["unofficial_key"]:
            out.append(f"- **Answers from an unofficial key ({len(un['unofficial_key'])}):** "
                       + ", ".join(L.q_short(q) for q in un["unofficial_key"]) + ".")
        if un["no_answer"]:
            out.append(f"- **No answer yet ({len(un['no_answer'])}):** worked solutions are generated and checked in M4: "
                       + ", ".join(L.q_short(q) for q in un["no_answer"]) + ".")
        for c in un["caveats"]:
            out.append(f"- **{L.q_short(c['id'])}:** {c['caveat']}")
        out.append("")

    # ------------------------------------------------------------------ method and sources
    st = index.get("stats", {})
    out += ["## How the numbers are made", "",
            "- A topic's share of a paper is the marks it got ÷ the paper's total; a question's marks are split evenly "
            "between its topics. Papers are averaged, weighted by their relevance.",
            "- That is blended with slide emphasis (the topic's share of all covered slides), the slides counting as one "
            "more paper. With no papers, slide emphasis is all there is.",
            "- Points = share × the exam's weight in the grade, summed over exams. Topics making up the first 50% of "
            "points are **high**, the next 30% **med**, the rest **low**.",
            "- Sample questions have no marks: they are listed and help decide each topic's mode, but don't move shares.",
            "", "## Sources", "",
            f"- {st.get('sources', 0)} sources ingested: " + ", ".join(f"{n} {k}" for k, n in st.get("by_kind", {}).items())
            + f"; {st.get('image_only', 0)} image-only pages read visually; {len(index.get('skipped', []))} files skipped "
            "(listed in `corpus/index.json`).", ""]
    return "\n".join(out).rstrip() + "\n"
